const express = require("express");
const router = express.Router();
const { signup } = require("../controllers/auth/signup");
const { signin } = require("../controllers/auth/signin");
const { userDetails } = require("../controllers/auth/userDetails");
const { authenticate } = require("../middlewares/authenticate");
router.post("/signup", signup);
router.post("/signin", signin);
router.get("/userDetails", authenticate, userDetails);
module.exports = router;
